### ISSUE TITLE
prelude-browser is unusable

### ISSUE THREAD

**Issue by Fresheyeball** [gkz/prelude-ls#73]
the minified version does not attach `prelude` to anything, and the unminified version just errors out. Also the website says to use `npm install prelude-ls` and then point to the browser version, but the browser version is not include in the npm package.

**Comment by peterjeliot** [comment]
I just found this, after wrestling with this problem for a while. Definitely needs to be in the documentation.

**Comment by Fresheyeball** [comment]
Browserify: dramatically increasing payload for browsers, in exchange for the beauty of `require` and `exports`. Its magic alright.

**Comment by gkz** [comment]
I feel the documentation is fairly straight forward...

```
For use in the browser, just include the prelude-browser-min.js file, and then use prelude = require 'prelude-ls'
```

You don't need to use browserify or require.js or anything, the above is all there is to it.

**Comment by peterjeliot** [comment]
Ah, yes. Unfortunately I was using the livescript-rails gem, and "require" isn't included, and prelude is simply put in the global scope. The instructions on the site don't quite work with that setup.

Also unfortunately, it appears that the gem has not been updated in some years, and has no issues page.

**Comment by vindarel** [comment]
>    For use in the browser, just include the prelude-browser-min.js file, and then use prelude = require 'prelude-ls'

indeed this works with bower, but there is no such `prelude-browser-min.js` when using npm, as Fresheyeball pointed out. How can we do then ? ([more detailed SO question](https://stackoverflow.com/questions/43939731/installing-livescript-and-prelude-ls-with-npm-and-a-gulpfile-is-there-no-prelu)).

with bower I included the `prelude-browser-min.js` file and I could

        {Obj, join, etc} = require 'prelude-ls'

now with the npm installation, I try to include (using gulp) the `*js` files out there (Obj.js etc) but I get a "module is not define" because of an "import" line somewhere.
